complexity:
  ComplexMethod:
    threshold: 20
  LongParameterList:
    functionThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 20

coroutines:
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    classPattern: '[A-Z][a-zA-Z0-9]*'

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
  MaxLineLength:
    maxLineLength: 120